export const BLIZZARD_API_PROFILE_NAMESPACE="profile-classic1x-eu"
export const BLIZZARD_API_STATIC_NAMESPACE="static-1.15.6_58725-classic1x-eu"
export const BLIZZARD_API_REGION="eu"
export const BLIZZARD_API_LOCALE="en_US"
export const GUILD_NAME="Everlasting Vendetta"
export const GUILD_SLUG="everlasting-vendetta"
export const GUILD_ID="2239011"
export const REALM_ID="5826"
export const REALM_NAME="Living Flame"
export const REALM_SLUG="living-flame"

